export {default as Home} from "./Home" 
export {default as Details} from "./Details" 
export {default as Profile} from "./Profile" 
export {default as Friends} from "./Friends" 
export {default as Search} from "./Search" 